apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-system-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-system-api
  template:
    metadata:
      labels:
        app: school-system-api
    spec:
      containers:
        - name: school-system-api
          image: baiks384/school-system-api
          ports:
            - containerPort: 8064
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          env:
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://dpg-d0q0108dl3ps73b6e760-a.oregon-postgres.render.com:5432/school_system_98fu
            - name: SPRING_DATASOURCE_USERNAME
              value: baiks
            - name: SPRING_DATASOURCE_PASSWORD
              value: CSlBkrVeNEHgDIfxCnvuDluHKib8d9Q1
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: school_system_98fu
            - name: SPRING_JPA_SHOW-SQL
              value: "1"
            - name: SPRING_HIKARI_AUTO-COMMIT
              value: "1"
            - name: SPRING_HIKARI_MINIMUM-IDLE
              value: "5"
            - name: SPRING_HIKARI_MAXIMUM-POOL-SIZE
              value: "20"
            - name: SPRING_HIKARI_CONNECTION-TIMEOUT
              value: "30000"
            - name: SPRING_HIKARI_IDLE-TIMEOUT
              value: "600000"
            - name: SPRING_HIKARI_MAX-LIFETIME
              value: "1800000"
            - name: SPRING_MAIL_HOST
              value: paulkimani.net
            - name: SPRING_MAIL_PORT
              value: "465"
            - name: SPRING_MAIL_USERNAME
              value: developer@paulkimani.net
            - name: SPRING_MAIL_PASSWORD
              value: Jaduongmapeng@123
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "false"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE
              value: "true"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT
              value: "10000"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT
              value: "10000"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT
              value: "1000"
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_GROUP-ID
              value: school_grp
            - name: SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET
              value: earliest
            - name: SPRING_KAFKA_CONSUMER_KEY-DESERIALIZER
              value: org.apache.kafka.common.serialization.StringDeserializer
            - name: SPRING_KAFKA_CONSUMER_VALUE-DESERIALIZER
              value: org.apache.kafka.common.serialization.StringDeserializer
            - name: SPRING_KAFKA_PRODUCER_KEY-SERIALIZER
              value: org.apache.kafka.common.serialization.StringSerializer
            - name: SPRING_KAFKA_PRODUCER_VALUE-SERIALIZER
              value: org.apache.kafka.common.serialization.StringSerializer
            - name: SERVER_PORT
              value: "8064"
            - name: DEV_URL
              value: http://localhost:8064
            - name: PROD_URL
              value: http://prod:8064
            - name: JWT_SECRET
              value: web-api@2024
            - name: JWT_EXPIRYINMINS
              value: "900"
            - name: SMS_URL
              value: https://sms.textsms.co.ke/api/services/sendsms/
            - name: SMS_PARTNER_ID
              value: "12362"
            - name: SMS_API_KEY
              value: 773ac3416a5b3f7cb26dbccad158c929
            - name: SMS_SHORTCODE
              value: TextSMS
            - name: SMS_PASS_TYPE
              value: plain

---
apiVersion: v1
kind: Service
metadata:
  name: school-system-api
spec:
  selector:
    app: school-system-api
  ports:
    - protocol: TCP
      port: 8064
      targetPort: 8064
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP