apiVersion: v1
kind: Service
metadata:
  name: school-system-service
spec:
  type: NodePort
  selector:
    app: school-system-api
  ports:
    - port: 8064
      targetPort: 8064
      nodePort: 30064
