spring:
  datasource:
    url: jdbc:h2:mem:promoquoter?createDatabaseIfNotExist=true;DB_CLOSE_DELAY=-1;
    username: root
    password: Baiks@123
    driverClassName: org.h2.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      minimumIdle: 10
      maximumPoolSize: 200
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
  level:
    web: DEBUG
    root: INFO
jwt:
  secret: Z2F0ZXdheWFwaTIwMjVXeXpRbU1jRGd6b1RYaEZ0Q0hYeXRCeGdRYkZvTnFRVmRZemlKT2p3a1NwRFRkTHg1Ug==
  expiryInMins: 15